# Please ping @DilumAluthge when making any changes to this file.

# Here are some steps that we take in this workflow file for security reasons:
# 1. We do not checkout any code.
# 2. We only run actions that are defined in a repository in the `JuliaLang` GitHub organization.
# 3. We do not give the `GITHUB_TOKEN` any permissions.
# 4. We only give the Buildkite API token (`BUILDKITE_API_TOKEN_RETRY`) the minimum necessary
#    set of permissions.

# Important note to Buildkite maintainers:
# In order to make this work, you need to tell Buildkite that it should NOT create a brand-new
# build when someone closes and reopens a pull request. To do so:
# 1. Go to the relevant pipeline (e.g. https://buildkite.com/julialang/julia-master).
# 2. Click on the "Pipeline Settings" button.
# 3. In the left sidebar, under "Pipeline Settings", click on "GitHub".
# 4. In the "GitHub Settings", under "Build Pull Requests", make sure that the "Skip pull
#    request builds for existing commits" checkbox is checked. This is the setting that tells
#    Buildkite that it should NOT create a brand-new build when someone closes and reopens a
#    pull request.
# 5. At the bottom of the page, click the "Save GitHub Settings" button.

name: Retry Failed Buildkite Jobs

on:
  # When using the `pull_request_target` event, all PRs will get access to secret environment
  # variables (such as the `BUILDKITE_API_TOKEN_RETRY` secret environment variable), even if
  # the PR is from a fork. Therefore, for security reasons, we do not checkout any code in
  # this workflow.
  pull_request_target:
    types: [ reopened ]

  # TODO: delete the following `workflow_dispatch` section (once we have completely transitioned from Buildbot to Buildkite)
  workflow_dispatch:
    inputs:
      PULL_REQUEST_NUMBER:
        description: 'The number of the pull request:'
        required: true

# We do not give the `GITHUB_TOKEN` any permissions.
permissions:
  statuses: none

jobs:
  retry:
    name: retry
    runs-on: ubuntu-latest
    if: github.repository == 'JuliaLang/julia'
    steps:
      # For security reasons, we do not checkout any code in this workflow.
      - if: github.event_name == 'pull_request_target'
        run: |
          echo "pr_number=${{ github.event.number }}" >> $GITHUB_ENV

      # TODO: delete the following three lines (once we have completely transitioned from Buildbot to Buildkite)
      - if: github.event_name == 'workflow_dispatch'
        run: |
          echo "pr_number=${{ github.event.inputs.PULL_REQUEST_NUMBER }}" >> $GITHUB_ENV

      - run: |
          echo "The pull request number is: ${{ env.pr_number }}"
      - uses: JuliaLang/retry-buildkite@057f6f2d37aa29a57b7679fd2af0df1d9f9188b4
        with:
          buildkite_api_token: ${{ secrets.BUILDKITE_API_TOKEN_RETRY }}
          buildkite_organization_slug: 'julialang'
          buildkite_pipeline_slug: 'julia-master'
          pr_number: ${{ env.pr_number }}
